### ISSUE TITLE
TTCN-3 language server cannot go to right definition if there are multiple definitions in different modules.

### ISSUE THREAD

**Issue by hhk0571** [nokia/ntt#172]
**Describe the bug**
TTCN-3 language server cannot go to right definition if there are multiple definitions in different modules.

**To Reproduce**
1. Install VS Code, git-bash, and MINGW64, integrated git-bash to VS Code by setting "terminal.integrated.shell.windows"
2. In VS Code, install TTCN-3 extension
3. In VS Code, enable ttcn3 language server
3. In VS Code, open ttcn3 project folder
4. In VS Code, select one function which has multiple definitions in several modules, press F12 to go to definition

**Expected behavior**
the "go to definition" didn't work, it hints no definition found.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Wind10
 - IDE: VS Code
 - Terminal: git-bash (MINGW64 installed)

**Additional context**
No

**Comment by 5nord** [comment]
Thanks for reporting this issue. The behaviour you experience is very simple to what a ctags-extension would show.  
There are actually two issues:

#### erroneous ambiguous references
The standard states that ambiguous references are to be considered as an input error. The current language server implementation therefore always jumps to the first hit, because it assumes there are no ambiguous definitions.   

This assumption might be correct, but it is not very helpful. I think the language server should simply point to all possible definitions and let the user choose.

#### ignored module prefixes
Ambigious references can be resolved by a module prefix. For example:
```
module test {
	import from B all;
	import from C all;
	control {
		C.foo() // <-- module C prefix.
	}
}
	
module A { function foo() { log("I am defined in module A") } }
module B { function foo() { log("I am defined in module B") } }
module C { function foo() { log("I am defined in module C") } }
```
However, evaluating expressions and thus resolving module prefixes is not implemented yet.

The first issue we intend to fix for the next bigger release in a couple of weeks. For the second issue I cannot make any promises yet.
